version: '3.8'

services:
  amrf-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: amrf-web-dev
    ports:
      - "5174:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
