version: '3.8'

services:
  amrf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amrf-web
    ports:
      - "5174:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
